from __future__ import annotations

REST_OF_WORLD_LEAGUE = "Reste du monde"
NATIONAL_TEAMS_LEAGUE = "Selections nationales"
LIGA_PORTUGAL_LEAGUE = "Liga Portugal"

CATEGORY_DEFINITIONS = [
    {"key": "national-teams", "env_var": "YUPOO_CATEGORY_NATIONAL_TEAMS_URL", "league": NATIONAL_TEAMS_LEAGUE, "country": None, "is_retro": False},
    {"key": "la-liga", "env_var": "YUPOO_CATEGORY_LA_LIGA_URL", "league": "La Liga", "country": "Espagne", "is_retro": False},
    {"key": "premier-league", "env_var": "YUPOO_CATEGORY_PREMIER_LEAGUE_URL", "league": "Premier League", "country": "Angleterre", "is_retro": False},
    {"key": "serie-a", "env_var": "YUPOO_CATEGORY_SERIE_A_URL", "league": "Serie A", "country": "Italie", "is_retro": False},
    {"key": "ligue-1", "env_var": "YUPOO_CATEGORY_LIGUE_1_URL", "league": "Ligue 1", "country": "France", "is_retro": False},
    {"key": "bundesliga", "env_var": "YUPOO_CATEGORY_BUNDESLIGA_URL", "league": "Bundesliga", "country": "Allemagne", "is_retro": False},
    {"key": "liga-portugal", "env_var": "YUPOO_CATEGORY_LIGA_PORTUGAL_URL", "league": LIGA_PORTUGAL_LEAGUE, "country": "Portugal", "is_retro": False},
    {"key": "other-leagues", "env_var": "YUPOO_CATEGORY_OTHER_LEAGUES_URL", "league": REST_OF_WORLD_LEAGUE, "country": None, "is_retro": False},
    {"key": "retro", "env_var": "YUPOO_CATEGORY_RETRO_URL", "league": None, "country": None, "is_retro": True},
]

LEAGUE_COUNTRY = {
    "Ligue 1": "France",
    "Premier League": "Angleterre",
    "La Liga": "Espagne",
    "Serie A": "Italie",
    "Bundesliga": "Allemagne",
    LIGA_PORTUGAL_LEAGUE: "Portugal",
}

PATCHES_BY_LEAGUE = {
    NATIONAL_TEAMS_LEAGUE: ["world_cup", "nations_league", "can", "copa_america", "gold_cup", "afc_cup"],
    "Ligue 1": ["ligue1_winner", "coupe_de_france", "trophee_champions", "ucl", "uel", "uecl", "uefa_super_cup"],
    "Premier League": ["pl_winner", "fa_cup", "efl_cup", "ucl", "uel", "uecl", "uefa_super_cup"],
    "La Liga": ["laliga_winner", "copa_del_rey", "supercopa", "ucl", "uel", "uecl", "uefa_super_cup"],
    "Serie A": ["serie_a_winner", "coppa_italia", "supercoppa", "ucl", "uel", "uecl", "uefa_super_cup"],
    "Bundesliga": ["bundesliga_winner", "dfb_pokal", "ucl", "uel", "uecl", "uefa_super_cup"],
    LIGA_PORTUGAL_LEAGUE: ["ucl", "uel", "uecl", "uefa_super_cup", "club_world_cup"],
    REST_OF_WORLD_LEAGUE: ["ucl", "uel", "uecl", "uefa_super_cup", "club_world_cup"],
}

ENTITY_ALIASES = {
    "paris saint germain": ("Paris Saint-Germain", "France", "Ligue 1"),
    "psg": ("Paris Saint-Germain", "France", "Ligue 1"),
    "marseille": ("Olympique de Marseille", "France", "Ligue 1"),
    "om": ("Olympique de Marseille", "France", "Ligue 1"),
    "monaco": ("AS Monaco", "France", "Ligue 1"),
    "arsenal": ("Arsenal", "Angleterre", "Premier League"),
    "chelsea": ("Chelsea", "Angleterre", "Premier League"),
    "liverpool": ("Liverpool", "Angleterre", "Premier League"),
    "manchester city": ("Manchester City", "Angleterre", "Premier League"),
    "man city": ("Manchester City", "Angleterre", "Premier League"),
    "manchester united": ("Manchester United", "Angleterre", "Premier League"),
    "man utd": ("Manchester United", "Angleterre", "Premier League"),
    "tottenham": ("Tottenham", "Angleterre", "Premier League"),
    "spurs": ("Tottenham", "Angleterre", "Premier League"),
    "newcastle": ("Newcastle", "Angleterre", "Premier League"),
    "aston villa": ("Aston Villa", "Angleterre", "Premier League"),
    "brighton": ("Brighton", "Angleterre", "Premier League"),
    "real madrid": ("Real Madrid", "Espagne", "La Liga"),
    "barcelona": ("FC Barcelone", "Espagne", "La Liga"),
    "fc barcelona": ("FC Barcelone", "Espagne", "La Liga"),
    "barca": ("FC Barcelone", "Espagne", "La Liga"),
    "atletico madrid": ("Atletico Madrid", "Espagne", "La Liga"),
    "inter milan": ("Inter Milan", "Italie", "Serie A"),
    "inter": ("Inter Milan", "Italie", "Serie A"),
    "ac milan": ("AC Milan", "Italie", "Serie A"),
    "juventus": ("Juventus", "Italie", "Serie A"),
    "napoli": ("Naples", "Italie", "Serie A"),
    "roma": ("AS Rome", "Italie", "Serie A"),
    "lazio": ("Lazio", "Italie", "Serie A"),
    "bayern munich": ("Bayern Munich", "Allemagne", "Bundesliga"),
    "bayern": ("Bayern Munich", "Allemagne", "Bundesliga"),
    "borussia dortmund": ("Borussia Dortmund", "Allemagne", "Bundesliga"),
    "dortmund": ("Borussia Dortmund", "Allemagne", "Bundesliga"),
    "bayer leverkusen": ("Bayer Leverkusen", "Allemagne", "Bundesliga"),
    "stuttgart": ("Stuttgart", "Allemagne", "Bundesliga"),
    "sporting cp": ("Sporting CP", "Portugal", LIGA_PORTUGAL_LEAGUE),
    "sporting lisbon": ("Sporting CP", "Portugal", LIGA_PORTUGAL_LEAGUE),
    "sporting": ("Sporting CP", "Portugal", LIGA_PORTUGAL_LEAGUE),
    "benfica": ("Benfica", "Portugal", LIGA_PORTUGAL_LEAGUE),
    "fc porto": ("FC Porto", "Portugal", LIGA_PORTUGAL_LEAGUE),
    "porto": ("FC Porto", "Portugal", LIGA_PORTUGAL_LEAGUE),
    "braga": ("Braga", "Portugal", LIGA_PORTUGAL_LEAGUE),
    "ajax": ("Ajax", "Pays-Bas", REST_OF_WORLD_LEAGUE),
    "celtic": ("Celtic", "Ecosse", REST_OF_WORLD_LEAGUE),
    "boca juniors": ("Boca Juniors", "Argentine", REST_OF_WORLD_LEAGUE),
    "river plate": ("River Plate", "Argentine", REST_OF_WORLD_LEAGUE),
    "flamengo": ("Flamengo", "Bresil", REST_OF_WORLD_LEAGUE),
    "santos": ("Santos", "Bresil", REST_OF_WORLD_LEAGUE),
    "club america": ("Club America", "Mexique", REST_OF_WORLD_LEAGUE),
    "france": ("France", "France", NATIONAL_TEAMS_LEAGUE),
    "england": ("Angleterre", "Angleterre", NATIONAL_TEAMS_LEAGUE),
    "spain": ("Espagne", "Espagne", NATIONAL_TEAMS_LEAGUE),
    "germany": ("Allemagne", "Allemagne", NATIONAL_TEAMS_LEAGUE),
    "portugal": ("Portugal", "Portugal", NATIONAL_TEAMS_LEAGUE),
    "italy": ("Italie", "Italie", NATIONAL_TEAMS_LEAGUE),
    "netherlands": ("Pays-Bas", "Pays-Bas", NATIONAL_TEAMS_LEAGUE),
    "belgium": ("Belgique", "Belgique", NATIONAL_TEAMS_LEAGUE),
    "usa": ("Etats-Unis", "Etats-Unis", NATIONAL_TEAMS_LEAGUE),
    "united states": ("Etats-Unis", "Etats-Unis", NATIONAL_TEAMS_LEAGUE),
    "mexico": ("Mexique", "Mexique", NATIONAL_TEAMS_LEAGUE),
    "brazil": ("Bresil", "Bresil", NATIONAL_TEAMS_LEAGUE),
    "brasil": ("Bresil", "Bresil", NATIONAL_TEAMS_LEAGUE),
    "argentina": ("Argentine", "Argentine", NATIONAL_TEAMS_LEAGUE),
    "morocco": ("Maroc", "Maroc", NATIONAL_TEAMS_LEAGUE),
    "algeria": ("Algerie", "Algerie", NATIONAL_TEAMS_LEAGUE),
    "colombia": ("Colombie", "Colombie", NATIONAL_TEAMS_LEAGUE),
    "japan": ("Japon", "Japon", NATIONAL_TEAMS_LEAGUE),
    "croatia": ("Croatie", "Croatie", NATIONAL_TEAMS_LEAGUE),
    "nigeria": ("Nigeria", "Nigeria", NATIONAL_TEAMS_LEAGUE),
}
